export const previewInfo = {
    title: [
        "After You've Learned Dual Blades for 5 Minutes",
        "I can't believe I'm playing this... | EEZYCRAFT #1 (Minecraft)",
        'Pokémon JavaScript Game Tutorial with HTML Canvas',
        "Becoming BIG BOY FARMERS in Minecraft (some slight Hixen betrayal.. sorry bru...) | EEZYCRAFT #3",
        "MHR Sunbreak: Status Trigger is actually OP",
        "Building MY FIRST HOUSE.. then this FREAK Ruined EVERYTHING... | EEZYCRAFT #2",
        "MHW Iceborne | After you've killed 1000 Fatalis",
        "Exploring DANGEROUS CAVES in Minecraft! (I wanna go home.) | EEZYCRAFT #4",
        "The \"Hixen's Revenge\" Episode | EEZYCRAFT #5",
    ],
    thumbnailSrc: [
        'thumbnails/dual.webp',
        'thumbnails/b1.jpeg',
        'thumbnails/hq720.webp',
        'thumbnails/b3.jpeg',
        'thumbnails/diablos.webp',
        'thumbnails/b2.jpeg',
        "thumbnails/fatalis.webp",
        'thumbnails/b4.jpeg',
        'thumbnails/b5.jpeg',
    ],
    videoTime: [
        '2:29',
        '36:00',
        '7:16:36',
        '40:25',
        '2:55',
        '39:29',
        '6:36',
        '42:29',
        '47:04',
    ],
    pfpSrc: [
        'channelpfp/tds.jpg',
        'channelpfp/berlin.jpg',
        'channelpfp/chris.jpg',
        'channelpfp/berlin.jpg',
        'channelpfp/tds.jpg',
        'channelpfp/berlin.jpg',
        'channelpfp/tds.jpg',
        'channelpfp/berlin.jpg',
        'channelpfp/berlin.jpg',

    ],
    creator: [
        'Team DarkSide',
        'Berleezy',
        'Chris Courses',
        'Berleezy',
        'Team DarkSide',
        'Berleezy',
        'Team DarkSide',
        'Berleezy',
        'Berleezy',

    ],
    stats: [
        '87K views \u00B7 3 days ago',
        '1.6M views \u00B7 2 years ago',
        '699K views \u00B7 7 months ago',
        '1.1M views \u00B7 1 year ago',
        '164K views \u00B7 1 month ago',
        '1M views \u00B7 1 year ago',
        '4.5M views \u00B7 1 year ago',
        '1M views \u00B7 1 year ago',
        '982K views \u00B7 1 year ago',
    ]
}
